// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lssoajyoctxdpmbhzvto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc29hanlvY3R4ZHBtYmh6dnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjE0NDIsImV4cCI6MjA2NDkzNzQ0Mn0.T5xH1Hvi6f93BVBHlVDO92TtOxt1d7U3Q9QMmg4j9YU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
